### ISSUE TITLE
Is it possible to run bitsandbytes with 2060RTX 6GB on Windows 10? 

### ISSUE THREAD

**Issue by healthyfat** [james-things/bitsandbytes-prebuilt-all_arch#2]

**Comment by james-things** [comment]
It should run, though you may have trouble running tasks on 6GB. What are you planning to use bnb for?

**Comment by healthyfat** [comment]
I had an issue running Kohya's GUI and was wondering if bitsandbytes supports my platform. It was something else after all and I can run Lora training now.

**Comment by james-things** [comment]
Ah, well glad you got it sorted out!
