### ISSUE TITLE
Feature request - Compile latest bitsandbytes which supports int8 on ALL GPUs!

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [james-things/bitsandbytes-prebuilt-all_arch#3]
I would kindly request you to please compile the latest bitsandbytes version ( 0.37.0 ) which now supports int8 matmul on ALL GPUs. I have a GTX 1060 6GB and it would be awesome to have it working with 8bitmode with Pygmalion.

**Comment by james-things** [comment]
I'll take a look at it later on today for you. I had given this some thought for 0.36.0, but saw an open issue about regression during training and decided to skip it and just clarify that this repo is 0.35.0.

I still have the build environment preserved so it should be no problem. Check back tonight. :) 

Edit: became busy with something - will still try to get to it, if not today, tomorrow!

**Comment by james-things** [comment]
Pushed a build for you to try out. Haven't tested it myself, but no errors during compilation to report!
